development:
  adapter:  postgresql
  encoding: unicode
  host:     localhost
  pool:     5
  database: jct_development

test:
  adapter:  postgresql
  encoding: unicode
  host:     localhost
  pool:     5
  database: jct_test

production:
  adapter:  postgresql
  encoding: unicode
  host:     localhost
  pool:     5
  database: jct_production